# Generated by Django 4.0.5 on 2022-06-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leaf_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaf_model',
            name='leaf_image',
            field=models.ImageField(default='', upload_to='Leaf_App/Images'),
        ),
    ]
