# Generated by Django 4.0.5 on 2022-06-26 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Leaf_App', '0002_leaf_model_leaf_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaf_model',
            name='leaf_name',
        ),
    ]
